FROM oven/bun:latest

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl

COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json

COPY ./package-lock.json ./package-lock.json

COPY ./turbo.json ./turbo.json

COPY ./packages ./packages

COPY ./apps/web ./apps/web

RUN bun install

RUN bun run db:generate

RUN bun run build

EXPOSE 3000

CMD [ "bun", "start:web" ]