FROM oven/bun:latest

WORKDIR /usr/src/app

COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json

COPY ./package-lock.json ./package-lock.json

COPY ./turbo.json ./turbo.json

COPY ./packages ./packages

COPY ./apps/http-server ./apps/http-server

RUN apt-get update -y && apt-get install -y openssl && apt-get install -y vim

RUN bun install

RUN bun run db:generate

EXPOSE 3001

CMD [ "bun", "start:http-server" ]