FROM oven/bun:latest

WORKDIR /usr/src/app

COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json

COPY ./package-lock.json ./package-lock.json

COPY ./turbo.json ./turbo.json

COPY ./packages ./packages

COPY ./apps/ws-server ./apps/ws-server

RUN apt-get update -y && apt-get install -y openssl

RUN bun install

RUN bun run db:generate

EXPOSE 8081

CMD [ "bun", "start:ws-server" ]
