name: Deploy FRONTEND

on:
  push:
    branches:
        - "main"
    paths:
      - "apps/web/**"
      - "docker/Dockerfile.web"
      - ".github/workflows/cd_web.yml" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.web
          push: true
          tags: heysharan/todo-app-frontend:latest,heysharan/todo-app-frontend:${{ github.sha }}

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 54.163.223.140
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          script: |
            sudo docker pull heysharan/todo-app-frontend:${{ github.sha }} && sudo docker stop todo-app-frontend && sudo docker rm todo-app-frontend && sudo docker run --name todo-app-frontend -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -d -p 3000:3000 heysharan/todo-app-frontend:${{ github.sha }}